#!/bin/bash
dev="$1"
if [[ !( -e "/dev/$dev" ) ]]; then
	echo Device $dev does not exist
	exit 1
fi
jarchcd2 -dev /dev/$dev -rip
jarchcd2 -dev /dev/$dev -rip -single
jarch-audio-to-wav
jarchcd2 -dev /dev/$dev -rip -verify
jarchcd2 -dev /dev/$dev -rip
jarchcd2 -dev /dev/$dev -rip -single -noskip
jarchcd2 -dev /dev/$dev -rip -verify
jarchcd2 -dev /dev/$dev -rip -noskip
jarch-audio-to-wav
for i in {1,2,3,4,5,6,7,8,9}; do jarchcd2 -dev /dev/$dev -rip -single -noskip; jarchcd2 -dev /dev/$dev -rip -single -noskip -verify; done
rm -f cdrom-image.timeout.ripfail.ripmap
for i in {1,2,3,4,5,6,7,8,9}; do jarchcd2 -dev /dev/$dev -rip -single -noskip; jarchcd2 -dev /dev/$dev -rip -single -noskip -verify; done
rm -f cdrom-image.timeout.ripfail.ripmap
jarchcd2 -dev /dev/$dev -rip -single -noskip; jarchcd2 -dev /dev/$dev -rip -single -noskip -verify
jarch-verify-data <cdrom-image.bin

