.\" Hey, EMACS: -*- nroff -*-
.\" jarchdvd2.1 is copyright (C) 2005
.\" Jonathan Campbell
.\"
.\" This is free documentation, see the latest version of the GNU General
.\" Public License for copying conditions. There is NO warranty.
.\"
.\" $Id: nano.1,v 1.41 2003/06/29 02:25:46 dolorous Exp $
.TH JARCHDVD2 "May 7th, 2005"
.\" Please adjust this date whenever revising the manpage.
.\"

.SH NAME
Jarchdvd2 \- Jonathan's DVD archival utility v2.0

.SH SYNOPSIS
.B jarchdvd2
.I [-dev device] [-bout logfile]
.br

.SH DESCRIPTION
This manual page documents briefly the \fBjarchdvd2\fP command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invoke bold face and italics, 
.\" respectively.
\fBjarchdvd2\fP is an intelligent DVD-ROM ripping and archiving utility.

.SH OPTIONS
.TP
.B \fI-dev /dev/xxx\fP
Instructs Jarchdvd2 to use block device \fI/dev/xxx\fP instead of /dev/dvd.
.TP
.B \-bout logfile
All output is written to file logfile as well as the console.

.SH SEE ALSO
.TP
.B jarchdvdkeys

.SH AUTHOR
Jonathan campbell <jcampbell@mdjk.com>

